version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  validation:
    build: ./validation
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    # Run as cron; alternatively, use a scheduler container

volumes:
  mongo-data: